### ISSUE TITLE
Problem parsing package

### ISSUE THREAD

**Issue by bigboi365** [LiamAbyss/Scorpion#13]
**Describe the bug**
Can't install apk, bug appears on  v0.4.3 and up.

**Screenshots**

![Screenshot_20210927-115014](https://user-images.githubusercontent.com/59653987/134886723-c025a11c-c81a-4bd8-8b2b-d871dd392343.png)

**Smartphone **
 - Device: Samsung GS6
 - OS: Android 7.0

**Comment by LiamAbyss** [comment]
Hello, thank you for your feedback ! 
Your android version is too old to encrypt things the way **Scorpion** does in the security update v0.4.3. 
I'll work a way around as soon as possible. I'll keep you updated on the progress of the resolution.

**Comment by LiamAbyss** [comment]
Hey !
The new update is live and should fix your problem.
Thank you for using **Scorpion** !

**Comment by bigboi365** [comment]
Yay!
Thank you!!
