### ISSUE TITLE
Vue semaine

### ISSUE THREAD

**Issue by ghislain955** [LiamAbyss/Scorpion#14]
Yo ! Une petite idée d'amélioration même si vous y avez déjà sûrement pensé :
Dans la vue planning, avoir le choix entre une vue "semaine" et une vue "jour" comme actuellement. La vue semaine serait comme sur aurion et quand on clique sur un cours une petite popup apparait avec les détails comme actuellement sur l'appli avec l'affichage détaillé d'un cours
Et aussi si vous avez la deter, en cliquant sur un cours on peut ajouter une notification avec un certain temps, ou plus simplement dans les paramètres choisir une notification pour chaque cours avec un temps par défaut (qu'on peut choisir) avant le début du cours

Sinon bravo et merci pour l'appli c'est super pratique !

**Comment by LiamAbyss** [comment]
Salut ! Merci pour ton retour !
J'ai créé deux issues pour tes deux idées, je ferme cette issue ci.
Issues : #15 et #16
