### ISSUE TITLE
Plantage au démarrage

### ISSUE THREAD

**Issue by Thiebosh** [LiamAbyss/Scorpion#18]
**Describe the bug**
Le premier démarrage de l'application plante. Il faut le démarrer une 2e fois pour qu'il fonctionne. Ce comportement a lieu dès que l'application n'est plus dans les applications en pause

**To Reproduce**
1. Vérifier que l'application n'est pas dans les applications en pause
2. Cliquer sur l'application une première fois
3. Voir l'application se fermer presque immédiatement (animation scorpion)

**Expected behavior**
Pas de plantage au démarrage

**Smartphone (please complete the following information):**
 - Device: xiaomi (Android)
 - Version: 0.5.2-beta

**Comment by LiamAbyss** [comment]
Ce bug a normalement été corrigé dans la dernière version, il était malheureusement dû à la recherche de mise à jour (donc impossible de savoir qu'il y avait une mise à jour). Passer à la 0.5.2.2-beta devrait régler ce problème.
